### ISSUE TITLE
TODO next update

### ISSUE THREAD

**Issue by brianwdavis** [brianwdavis/quadrangle#3]
- [ ] Add explicit tests, including various failures
- [ ] Add function to update JS src/store in `options()`/function to revert
- [ ] Probably remove `qr_v8_ls`; spawning new V8s isn't a performance drag on small images
- [ ] Add `option` to hide progress bars
- [ ] Upgrade README to proper Rmarkdown
- [ ] Add pixel-array-only example to README
- [ ] Round off `x`/`y` locations from JS engine
- [ ] CRAN!
